export function downloadCSV(
  users = [],
  volunteers = [],
  requests = []
) {
  const rows = [];

  // =========================
  // Report Header
  // =========================

  rows.push(["Bridge Admin Report"]);
  rows.push([
    `Generated: ${new Date().toLocaleDateString("en-GB")}`,
  ]);
  rows.push([
    "========================================",
  ]);
  rows.push([]);

  // =========================
  // Summary
  // =========================

  const approvedRequests = requests.filter(
    (request) => request.status === "Approved"
  ).length;

  const pendingRequests = requests.filter(
    (request) => request.status === "Pending"
  ).length;

  const rejectedRequests = requests.filter(
    (request) => request.status === "Rejected"
  ).length;

  const activeVolunteers = volunteers.filter(
    (volunteer) => volunteer.status === "Active"
  ).length;

  const pendingVolunteers = volunteers.filter(
    (volunteer) => volunteer.status === "Pending"
  ).length;

  const suspendedVolunteers = volunteers.filter(
    (volunteer) => volunteer.status === "Suspended"
  ).length;

  rows.push(["EXECUTIVE SUMMARY"]);
  rows.push([
    "----------------------------------------",
  ]);

  rows.push([`Total Users: ${users.length}`]);
  rows.push([
    `Total Volunteers: ${volunteers.length}`,
  ]);
  rows.push([
    `Total Requests: ${requests.length}`,
  ]);

  rows.push([]);

  rows.push([
    `Approved Requests: ${approvedRequests}`,
  ]);
  rows.push([
    `Pending Requests: ${pendingRequests}`,
  ]);
  rows.push([
    `Rejected Requests: ${rejectedRequests}`,
  ]);

  rows.push([]);

  rows.push([
    `Active Volunteers: ${activeVolunteers}`,
  ]);
  rows.push([
    `Pending Volunteers: ${pendingVolunteers}`,
  ]);
  rows.push([
    `Suspended Volunteers: ${suspendedVolunteers}`,
  ]);

  rows.push([]);
  rows.push([]);

  // =========================
  // Users
  // =========================

  rows.push([
    `REGISTERED USERS (${users.length})`,
  ]);

  rows.push([
    "Name",
    "Email",
    "Role",
    "Status",
    "Joined",
  ]);

  users.forEach((user) => {
    rows.push([
      user.name,
      user.email,
      user.role,
      user.status,
      user.joined,
    ]);
  });

  rows.push([]);
  rows.push([]);

  // =========================
  // Volunteers
  // =========================

  rows.push([
    `VOLUNTEERS (${volunteers.length})`,
  ]);

  rows.push([
    "Name",
    "Email",
    "Skill",
    "Hours Served",
    "Status",
  ]);

  volunteers.forEach((volunteer) => {
    rows.push([
      volunteer.name,
      volunteer.email,
      volunteer.skill,
      volunteer.hours,
      volunteer.status,
    ]);
  });

  rows.push([]);
  rows.push([]);

  // =========================
  // Requests
  // =========================

  rows.push([
    `REQUESTS (${requests.length})`,
  ]);

  rows.push([
    "Title",
    "Category",
    "Requested By",
    "Status",
  ]);

  requests.forEach((request) => {
    rows.push([
      request.title,
      request.category,
      request.user,
      request.status,
    ]);
  });

  rows.push([]);
  rows.push([
    "========================================",
  ]);
  rows.push(["End of Report"]);
  rows.push([
    "Generated by Bridge Admin Dashboard",
  ]);

  // =========================
  // Download
  // =========================

  const csvContent = rows
    .map((row) => row.join(","))
    .join("\n");

  const blob = new Blob([csvContent], {
    type: "text/csv;charset=utf-8;",
  });

  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");

  link.href = url;

  link.download = `bridge-admin-report-${new Date()
    .toISOString()
    .slice(0, 10)}.csv`;

  document.body.appendChild(link);

  link.click();

  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}